import { ComponentType } from 'react';
import {
  Activity,
  ArrowUpRight,
  Ban,
  Brain,
  Coins,
  CreditCard,
  DollarSign,
  FileText,
  Folder,
  Github,
  HelpCircle,
  History,
  Home,
  Key,
  Mail,
  MessageCircle,
  Newspaper,
  Pencil,
  Plus,
  Settings,
  ShieldCheck,
  User,
  Users,
  Zap,
} from 'lucide-react';
import {
  RiAddLine,
  RiBarChart2Line,
  RiCameraLensLine,
  RiChat2Line,
  RiClapperboardAiLine,
  RiCloudy2Fill,
  RiCloudyFill,
  RiCodeFill,
  RiDatabase2Line,
  RiDeleteBinLine,
  RiDiscordFill,
  RiEditLine,
  RiExchangeLine,
  RiEyeLine,
  RiFlashlightFill,
  RiGithubFill,
  RiGoogleFill,
  RiImage2Line,
  RiImageLine,
  RiKey2Fill,
  RiLockPasswordLine,
  RiMessage2Line,
  RiMovieLine,
  RiMusic2Line,
  RiNextjsFill,
  RiQuestionLine,
  RiRadioLine,
  RiRefreshLine,
  RiRobot2Line,
  RiScissors2Line,
  RiSoundModuleLine,
  RiTaskLine,
  RiTwitterXFill,
} from 'react-icons/ri';

const iconMap: Record<string, ComponentType<any>> = {
  // lucide icons (kept small and tree-shaken)
  Activity,
  ArrowUpRight,
  Ban,
  Brain,
  Coins,
  CreditCard,
  DollarSign,
  FileText,
  Folder,
  Github,
  HelpCircle,
  History,
  Home,
  Key,
  Mail,
  MessageCircle,
  Newspaper,
  Pencil,
  Plus,
  Settings,
  ShieldCheck,
  User,
  Users,
  Zap,

  // remix/react-icons (only the names we actually use)
  RiAddLine,
  RiBarChart2Line,
  RiCameraLensLine,
  RiChat2Line,
  RiClapperboardAiLine,
  RiCloudy2Fill,
  RiCloudyFill,
  RiCodeFill,
  RiDatabase2Line,
  RiDeleteBinLine,
  RiDiscordFill,
  RiEditLine,
  RiExchangeLine,
  RiEyeLine,
  RiFlashlightFill,
  RiGithubFill,
  RiGoogleFill,
  RiImage2Line,
  RiImageLine,
  RiKey2Fill,
  RiLockPasswordLine,
  RiMessage2Line,
  RiMovieLine,
  RiMusic2Line,
  RiNextjsFill,
  RiQuestionLine,
  RiRadioLine,
  RiRefreshLine,
  RiRobot2Line,
  RiScissors2Line,
  RiSoundModuleLine,
  RiTaskLine,
  RiTwitterXFill,
};

export function SmartIcon({
  name,
  size = 24,
  className,
  ...props
}: {
  name: string;
  size?: number;
  className?: string;
  [key: string]: any;
}) {
  const IconComponent =
    iconMap[name] || (name.startsWith('Ri') ? RiQuestionLine : HelpCircle);

  return <IconComponent size={size} className={className} {...props} />;
}
